### ISSUE TITLE
Warning: Parameter 2 to SyndicationDataQueries::posts_search() expected to be a reference, value given in /Applications/MAMP/htdocs/wordpress/wp-includes/class-wp-hook.php on line 298

### ISSUE THREAD

**Issue by Gaelan** [radgeek/feedwordpress#86] opened 2017-03-21 22:55 UTC
Appears as soon as I set up a feed on WP 4.7.3, PHP 7.1.0. Any idea what could be happening?

**Comment by BandonRandon** [comment] 2017-03-23 20:29
Hi @Gaelan I also ran into this and ended up just disabling the plugin. 

But to give you a starting place if you want to patch this, PHP 7.1 changed the way refrences work. (see: http://php.net/manual/en/language.references.php) the error comes from the `&` in front of values in functions like here:
https://github.com/radgeek/feedwordpress/blob/86e3579526e4bb9a70df01ff6bac279249a136ad/syndicationdataqueries.class.php#L41 

If you changed `function posts_search ($search, &$query) {` to `function posts_search ($search, $query) {` the warning would be resolved (you'll of course need to do this for each place where a `&$variable` is used.

**Comment by chasegawa** [comment] 2017-04-28 15:17
I see it as well and had to disable the plugin.

Warning: Parameter 2 to SyndicationDataQueries::posts_search() expected to be a reference, value given in /storage/h14/785/1479785/public_html/wp-includes/class-wp-hook.php on line 298

Warning: Parameter 2 to SyndicationDataQueries::posts_where() expected to be a reference, value given in /storage/h14/785/1479785/public_html/wp-includes/class-wp-hook.php on line 298

**Comment by radgeek** [comment] 2017-10-27 21:42
This issue should be resolved by the fix contained in @david-robinson-practiceweb 's pull request, which I merged into the most recent release of FeedWordPress. Thanks for the report, let me know if the problem is resolved on your end or if there's anything else that needs attention.

**Closed by radgeek** 2017-10-27 21:42 UTC
